### ISSUE TITLE
Group Levels of Detail not working in 3.5.stable

### ISSUE THREAD

**Issue by ksjfhor** [R3X-G1L6AME5H/Godot-LOD-Manager#1]
Hey, 
first of all, thank you for this addon.
Sadly for me it won't group the LOD 2 and 3.
Please see the Screenshot attached, I think because the grouping does not work, it won't load the LOD 2 and 3, because it will not notice them.

![grafik](https://user-images.githubusercontent.com/87974401/191905717-a928b434-4f1f-4bc0-a730-5cec8375aae6.png)

Also I am not sure if this is supposed to happen, but I cannot toggle the visibility of the nodes, but this is maybe because of the grouping, or not grouping.

I am getting this output when I hit the checkbox:
LOD Manager created 100 new knots. -> This is great.
Set group_levels_of_detail
Set group_levels_of_detail
LOD Manager created 0 new knots. -> This is sad.
Set group_levels_of_detail
Set group_levels_of_detail
LOD Manager created 0 new knots. -> This also.
Set group_levels_of_detail
Set group_levels_of_detail

I started with a fresh project and only downloaded Chunking and LOD from the assetlib, would be great if you could help me in any way, otherwise my fallout clone would be pretty lame lol.

Greetings

**Comment by R3X-G1L6AME5H** [comment]
A fellow fallout fan🤓; it is an honour to be of service.

So, the problem is likely in the naming scheme. The way the plugin groups nodes is by matching their prefixes.

For example if we had `Chunk001-lod1`, and you pressed the group button, it would search for any node with the **name** "Chunk001" that is followed by **suffix** `-lodN` i.e. `Chunk001-lod2` and `Chunk001-lod3`. 

What I notice is that unless you have 3100 nodes/chunks in your sceen, your node **name** is not the same throuought the **suffixes**.  If my guess is right, you have 100 nodes/chunks in your scene, and you haven't removed the 1, 2, 3 from your initial mesh name. In summary, Your `LOD_3001-lod3` should actually be `LOD_001-lod3`; your `LOD_2001-lod2` should be `LOD_001-lod2`; finally, your `LOD_1001-lod1` should be `LOD_001-lod1`.

Let me know if this resolves the issue. ✌️✌️✌️

**Comment by ksjfhor** [comment]
Thank you for your reply, when I do it the right way, "it just works".
Your guess was absolutly right. I have created 100 nodes with each having 3 LOD.
So there is no issue left and this can be closed :)

One thing: Would you recommend creating the collisons in blender by duping the planes adding -col to the name and make it a child of the duped parent ? (sorry if this is unclear, the shortcuts would be shift+d for duping and set parent to object with strg+p, after selecting child and parent, in the main window). Thats how I did it for now.

Greetings :)

**Comment by R3X-G1L6AME5H** [comment]
I never tried exporting collisions from blender to godot; did not even know it was possible. I would check if all the Collision nodes point to the same mesh. If so then I reccomend it.

While we are on topic of optimization, there is rarely a need to put collisions on level 2 and 3. Rarely will there be a need for actual physics simulation somewhere where the player can barely see it. Better just make a "guess" to what the simulation ammounted to when loading the chunk.
